SERVICES = (
    {
        "slug": "ventas-digitales",
        "code": "01",
        "category": "growth",
        "title": "Ventas digitales",
        "summary": "Organiza prospectos, cotizaciones y pedidos en un flujo que el equipo pueda seguir.",
        "description": "Diseñamos un proceso comercial visible de principio a fin para reducir oportunidades perdidas y mejorar el seguimiento.",
        "outcomes": (
            "Seguimiento centralizado",
            "Cotizaciones trazables",
            "Indicadores comerciales",
        ),
        "deliverables": (
            "Mapa del proceso comercial",
            "Tablero de oportunidades",
            "Plantillas y automatizaciones",
            "Guía operativa",
        ),
    },
    {
        "slug": "inventario-conectado",
        "code": "02",
        "category": "operations",
        "title": "Inventario conectado",
        "summary": "Convierte movimientos dispersos en existencias confiables y alertas accionables.",
        "description": "Conectamos entradas, salidas y reposición para que compras y ventas trabajen sobre la misma información.",
        "outcomes": ("Existencias visibles", "Alertas de reposición", "Menos ajustes manuales"),
        "deliverables": (
            "Catálogo normalizado",
            "Flujo de movimientos",
            "Alertas configuradas",
            "Panel de rotación",
        ),
    },
    {
        "slug": "automatizacion-operativa",
        "code": "03",
        "category": "operations",
        "title": "Automatización operativa",
        "summary": "Reduce tareas repetitivas sin convertir la operación en una caja negra.",
        "description": "Automatizamos pasos concretos con validaciones, registros y una ruta manual de respaldo.",
        "outcomes": ("Menos reprocesos", "Tiempos predecibles", "Trazabilidad de cambios"),
        "deliverables": (
            "Inventario de tareas",
            "Automatizaciones priorizadas",
            "Registro de ejecución",
            "Plan de contingencia",
        ),
    },
    {
        "slug": "datos-y-decisiones",
        "code": "04",
        "category": "growth",
        "title": "Datos y decisiones",
        "summary": "Transforma datos operativos en indicadores sencillos para decidir a tiempo.",
        "description": "Definimos métricas útiles y tableros comprensibles, evitando reportes que nadie consulta.",
        "outcomes": ("Una fuente de verdad", "Métricas acordadas", "Revisión periódica"),
        "deliverables": (
            "Diccionario de indicadores",
            "Tablero ejecutivo",
            "Alertas de desviación",
            "Rutina de seguimiento",
        ),
    },
    {
        "slug": "seguridad-practica",
        "code": "05",
        "category": "security",
        "title": "Seguridad práctica",
        "summary": "Protege accesos, información y continuidad sin frenar el trabajo diario.",
        "description": "Aplicamos controles proporcionales al riesgo y enseñamos al equipo por qué existen.",
        "outcomes": ("Accesos mínimos", "Respaldos verificables", "Respuesta preparada"),
        "deliverables": (
            "Evaluación de riesgos",
            "Matriz de accesos",
            "Política de respaldos",
            "Guía de incidentes",
        ),
    },
    {
        "slug": "plataforma-y-continuidad",
        "code": "06",
        "category": "security",
        "title": "Plataforma y continuidad",
        "summary": "Construye una base técnica observable, actualizable y preparada para recuperarse.",
        "description": "Organizamos despliegues, monitoreo y recuperación para que el crecimiento no dependa de improvisaciones.",
        "outcomes": ("Despliegues repetibles", "Estado observable", "Recuperación ensayada"),
        "deliverables": (
            "Arquitectura documentada",
            "Pipeline de entrega",
            "Monitoreo esencial",
            "Plan de recuperación",
        ),
    },
)

METHOD_STAGES = (
    {
        "code": "01",
        "title": "Descubrir",
        "text": "Entendemos el proceso, las personas, los datos y el riesgo actual.",
    },
    {
        "code": "02",
        "title": "Priorizar",
        "text": "Elegimos una mejora pequeña con valor medible y alcance controlado.",
    },
    {
        "code": "03",
        "title": "Implementar",
        "text": "Construimos, probamos y documentamos con seguridad desde el inicio.",
    },
    {
        "code": "04",
        "title": "Acompañar",
        "text": "Capacitamos, medimos resultados y preparamos la siguiente iteración.",
    },
)

CASE_SCENARIOS = (
    {
        "sector": "Comercio minorista",
        "title": "Inventario que acompaña las ventas",
        "challenge": "Existencias en hojas separadas y reposición reactiva.",
        "solution": "Catálogo unificado, movimientos trazables y alertas de mínimos.",
        "result": "Meta orientativa: reducir ajustes manuales y faltantes recurrentes.",
    },
    {
        "sector": "Servicios profesionales",
        "title": "Seguimiento comercial sin oportunidades perdidas",
        "challenge": "Contactos repartidos entre mensajes, correos y notas personales.",
        "solution": "Flujo de oportunidades, recordatorios y tablero de seguimiento.",
        "result": "Meta orientativa: responder más rápido y conocer el estado de cada oportunidad.",
    },
    {
        "sector": "Operación en crecimiento",
        "title": "Continuidad con controles simples",
        "challenge": "Accesos compartidos, respaldos no verificados y cambios manuales.",
        "solution": "Roles, copias verificables, registro de cambios y recuperación documentada.",
        "result": "Meta orientativa: reducir el impacto de errores e incidentes comunes.",
    },
)

PLANS = (
    {
        "slug": "norte-base",
        "name": "Norte Base",
        "eyebrow": "Ordenar un proceso crítico",
        "price_co": "$1.490.000",
        "price_pe": "S/ 1,450",
        "price_note_co": "COP · implementación desde",
        "price_note_pe": "PEN · implementación desde",
        "duration": "2 a 3 semanas",
        "audience": "Microempresa o equipo de hasta 5 personas",
        "featured": False,
        "description": "Para negocios que necesitan resolver un cuello de botella concreto y crear una base medible.",
        "features": (
            "Diagnóstico y línea base",
            "Un proceso priorizado",
            "Una solución funcional",
            "Controles básicos de seguridad",
            "Capacitación y documentación",
            "15 días de acompañamiento",
        ),
    },
    {
        "slug": "norte-conecta",
        "name": "Norte Conecta",
        "eyebrow": "Conectar operación y decisiones",
        "price_co": "$3.900.000",
        "price_pe": "S/ 3,800",
        "price_note_co": "COP · implementación desde",
        "price_note_pe": "PEN · implementación desde",
        "duration": "4 a 6 semanas",
        "audience": "Negocio en crecimiento con varias funciones",
        "featured": True,
        "description": "Para equipos que ya necesitan conectar dos frentes y reducir trabajo manual entre áreas.",
        "features": (
            "Todo lo incluido en Norte Base",
            "Dos procesos conectados",
            "Automatización priorizada",
            "Tablero de indicadores",
            "Matriz de accesos y respaldos",
            "30 días de acompañamiento",
        ),
    },
    {
        "slug": "norte-escala",
        "name": "Norte Escala",
        "eyebrow": "Construir una plataforma integral",
        "price_co": "A medida",
        "price_pe": "A medida",
        "price_note_co": "propuesta después del diagnóstico",
        "price_note_pe": "propuesta después del diagnóstico",
        "duration": "8 semanas o más",
        "audience": "Operación con múltiples áreas o integraciones",
        "featured": False,
        "description": "Para organizaciones que necesitan arquitectura, integraciones y entrega continua entre varias áreas.",
        "features": (
            "Hoja de ruta empresarial",
            "Múltiples procesos e integraciones",
            "Arquitectura y datos compartidos",
            "Pipeline DevSecOps",
            "Monitoreo y recuperación",
            "90 días de acompañamiento",
        ),
    },
)

PLAN_COMPARISON = (
    ("Procesos incluidos", "1", "2", "Según alcance"),
    ("Automatización", "Básica", "Priorizada", "Integral"),
    ("Panel de indicadores", "Línea base", "Incluido", "Multifuncional"),
    ("Seguridad", "Controles esenciales", "Accesos y respaldos", "DevSecOps completo"),
    ("Acompañamiento", "15 días", "30 días", "90 días"),
)
